
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Cart_Details
{

    public int P_id { get; set; }

    public string Sub_Product_Name { get; set; }

    public string Sub_Product_Price { get; set; }

    public string Sub_Product_TFN { get; set; }

    public string Sub_Product_MFD { get; set; }

    public string Sub_Product_Discount { get; set; }

    public Nullable<int> Product_Categoris { get; set; }

}

}
