
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Complaint
{

    public int CompliantID { get; set; }

    public string CustomerName { get; set; }

    public string CustomerAddress { get; set; }

    public string CustomerMobileNUmber { get; set; }

    public System.DateTime CompliantDate { get; set; }

    public System.DateTime CompliantCloseDate { get; set; }

    public string CompliantItem { get; set; }

    public decimal CompliantCharge { get; set; }

    public decimal CompliantPayment { get; set; }

    public string PaymentMode { get; set; }

}

}
