
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ProductMaster
{

    public int Product_id { get; set; }

    public string Product_name { get; set; }

    public string Description { get; set; }

    public Nullable<int> UnitperPrice { get; set; }

    public Nullable<int> marginPerUnit { get; set; }

}

}
