
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Product_Master
{

    public int P_id { get; set; }

    public string Product_Name { get; set; }

}

}
