
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PurchaseDetail
{

    public int id { get; set; }

    public string purchase_id { get; set; }

    public string product_name { get; set; }

    public string Description { get; set; }

    public string Quantity { get; set; }

    public string PurchaseDate { get; set; }

    public Nullable<decimal> price { get; set; }

    public string additionalComment { get; set; }

    public string SupplierName { get; set; }

}

}
