
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Regitration
{

    public int id { get; set; }

    public string username { get; set; }

    public string UserPassword { get; set; }

    public string Email { get; set; }

    public string mobile { get; set; }

    public string registerdate { get; set; }

    public string city { get; set; }

}

}
