

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class SainiShopEntities1 : DbContext
{
    public SainiShopEntities1()
        : base("name=SainiShopEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Complaint> Complaints { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<ProductMaster> ProductMasters { get; set; }

    public virtual DbSet<Sale> Sales { get; set; }

    public virtual DbSet<SupplierMaster> SupplierMasters { get; set; }

    public virtual DbSet<WattMaster> WattMasters { get; set; }

    public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }

    public virtual DbSet<Sales_Details> Sales_Details { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Regitration> Regitrations { get; set; }

    public virtual DbSet<Product_Master> Product_Master { get; set; }

    public virtual DbSet<Cart_Details> Cart_Details { get; set; }


    public virtual int productproc(Nullable<int> product_id, string product_name, Nullable<int> suppliers_id, Nullable<int> quantity, string description, Nullable<int> price)
    {

        var product_idParameter = product_id.HasValue ?
            new ObjectParameter("product_id", product_id) :
            new ObjectParameter("product_id", typeof(int));


        var product_nameParameter = product_name != null ?
            new ObjectParameter("product_name", product_name) :
            new ObjectParameter("product_name", typeof(string));


        var suppliers_idParameter = suppliers_id.HasValue ?
            new ObjectParameter("suppliers_id", suppliers_id) :
            new ObjectParameter("suppliers_id", typeof(int));


        var quantityParameter = quantity.HasValue ?
            new ObjectParameter("quantity", quantity) :
            new ObjectParameter("quantity", typeof(int));


        var descriptionParameter = description != null ?
            new ObjectParameter("description", description) :
            new ObjectParameter("description", typeof(string));


        var priceParameter = price.HasValue ?
            new ObjectParameter("price", price) :
            new ObjectParameter("price", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("productproc", product_idParameter, product_nameParameter, suppliers_idParameter, quantityParameter, descriptionParameter, priceParameter);
    }

}

}

