
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SaniShop.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Sales_Details
{

    public int id { get; set; }

    public string Sales_id { get; set; }

    public string Product_name { get; set; }

    public string Quantity { get; set; }

    public string Product_price { get; set; }

    public string Amount { get; set; }

    public string sales_date { get; set; }

    public Nullable<int> watt { get; set; }

    public Nullable<int> Wire_meter { get; set; }

    public string Description { get; set; }

    public string AdditionalComments { get; set; }

}

}
